### ISSUE TITLE
Broken link to dplyr vignette

### ISSUE THREAD

**Issue by thoat** [msr-ds3/coursework#37]
* __Issue__: `week1/README.md` line 115: http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html --> this URL opens a 404 Not Found page. 

* __Potential solution__: I guess the content has been moved here? https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html

@jhofman

**Comment by jhofman** [comment]
thanks @thoat! 

fixed in #37
